spring:
  application:
    name: backend
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate.ddl-auto: update #create-drop
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: TRACE
jwt:
  rsa-private-key: classpath:certificates/privateKey.pem
  rsa-public-key: classpath:certificates/publicKey.pem

springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: method
  packages-to-scan: edu.ntnu.idatt2105.backend.controller
